//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminal.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mc_Topaz.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  __   ___ _  ___  ___ _ _  _  ___
        ///|__] |__/ | |___ |___ | |\ | | __
        ///|__] |  \ | |___ |    | | \| |__|.
        /// </summary>
        internal static string BriefingLogo {
            get {
                return ResourceManager.GetString("BriefingLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the future, man has invented a time machine to travel back in time.
        ///An organization called &quot;The epoch council&quot; has been formed to rule over time travels.
        ///At the council&apos;s headquarters, the machine is kept and guarded 24 hours a day by the council&apos;s guards.
        ///The Council has created a time travel directive called &quot;The epoch directive&quot; or the &quot;directive&quot;.
        ///This directive determines how time travels should take place.
        ///
        ///Changing events in the past can have huge consequences in the future 
        ///and should be d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ _  _ ___ ____ ____ ___  _  _ ____ ___ _ ____ _  _
        ///| |\ |  |  |__/ |  | |  \ |  | |     |  | |  | |\ |
        ///| | \|  |  |  \ |__| |__/ |__| |___  |  | |__| | \|.
        /// </summary>
        internal static string IntroductionLogo {
            get {
                return ResourceManager.GetString("IntroductionLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  __   __   __  ___     ___  __   __   ___ _  _     ___ _  _ _  __  _  _  __
        ///|__| |__| |__   |     |___ |__| |  | |    |__|    |___ |\ | | | __ |\/| |__|
        ///|    |  | ___|  |     |___ |    |__| |___ |  |    |___ | \| | |__| |  | |  |.
        /// </summary>
        internal static string MenuLogo {
            get {
                return ResourceManager.GetString("MenuLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  __   __  ___ _  __  _  _ ____
        ///|  | |__|  |  | |  | |\ | |__  
        ///|__| |     |  | |__| | \| ___|.
        /// </summary>
        internal static string OptionsLogo {
            get {
                return ResourceManager.GetString("OptionsLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     ____             __     ______                 __       ______      _                      
        ///   / __ \____  _____/ /_   / ____/___  ____  _____/ /_     / ____/___  (_)___  ____ ___  ____ _
        ///  / /_/ / __ `/ ___/ __/  / __/ / __ \/ __ \/ ___/ __ \   / __/ / __ \/ / __ `/ __ `__ \/ __ `/
        /// / ____/ /_/ (__  ) /_   / /___/ /_/ / /_/ / /__/ / / /  / /___/ / / / / /_/ / / / / / / /_/ / 
        ////_/    \__,_/____/\__/  /_____/ .___/\____/\___/_/ /_/  /_____/_/ /_/_/\__, /_/ /_/ /_/\__,_/  
        ///                            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SplashLogoHorizontal {
            get {
                return ResourceManager.GetString("SplashLogoHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ______      ___           _______ ___________
        ///|   _  \    /   \         /       |           |
        ///|  |_)  |  /  ^  \       |   (----`---|  |----`
        ///|   ___/  /  /_\  \       \   \       |  |
        ///|  |     /  _____  \  .----)   |      |  |
        ///| _|    /__/     \__\ |_______/       |__|
        /// _______  ______     ______     ______  __    __
        ///|   ____||   _  \   /  __  \   /      ||  |  |  |
        ///|  |__   |  |_)  | |  |  |  | |  ,----&apos;|  |__|  |
        ///|   __|  |   ___/  |  |  |  | |  |     |   __   |
        ///|  |____ |  |      |  `--&apos;  | | [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SplashLogoVertical {
            get {
                return ResourceManager.GetString("SplashLogoVertical", resourceCulture);
            }
        }
    }
}
